In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv('ipl_scores_missing.csv')
print(df.isnull().sum()) 

df.info()

match_id        0
batting_team    2
bowling_team    1
venue           1
overs           2
wickets         3
runs_scored     4
run_rate        4
target          4
result          2
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   match_id      25 non-null     int64
 1   batting_team  23 non-null     object
 2   bowling_team  24 non-null     object
 3   venue         24 non-null     object
 4   overs         23 non-null     float64
 5   wickets       22 non-null     float64
 6   runs_scored   21 non-null     float64
 7   run_rate      21 non-null     float64
 8   target        21 non-null     float64
 9   result        23 non-null     object
dtypes: float64(5), int64(1), object(4)
memory usage: 2.1+ KB

In [25]:
num_cols =['match_id' , 'overs' , 'wickets' , 'runs_scored' , 'run_rate','target']

df[num_cols]=df[num_cols].fillna(df[num_cols].median())

cat_cols = ['batting_team' , 'bowling_team' , 'venue' , 'result']

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum()

match_id        0
batting_team    0
bowling_team    0
venue           0
overs           0
wickets         0
runs_scored     0
run_rate        0
target          0
result          0
dtype: int64

In [26]:
df.head()

,match_id,batting_team,bowling_team,venue,overs,wickets,runs_scored,run_rate,target,result
0,1,Mumbai Indians,Chennai Super Kings,Wankhede,20.0,4.0,187.0,9.35,175.0,win
1,2,Chennai Super Kings,Mumbai Indians,Chepauk,20.0,5.0,152.0,7.60,188.0,loss
2,3,Royal Challengers Bangalore,Kolkata Knight Riders,Chinnaswamy,20.0,3.0,175.0,10.20,189.0,win
3,4,Kolkata Knight Riders,Royal Challengers Bangalore,Sawai Mansingh,20.0,7.0,163.0,8.15,205.0,loss
4,5,Delhi Capitals,Rajasthan Royals,Kotla,20.0,5.0,178.0,8.75,165.0,win

In [27]:
venue_dummies = pd.get_dummies(df['venue'], drop_first=True)
df = pd.concat([df, venue_dummies], axis=1)
df = df.drop(columns=['venue'])

print(df.shape)
print(df.head(2))

(25, 16)
   match_id         batting_team         bowling_team  overs  wickets  \
0         1       Mumbai Indians  Chennai Super Kings   20.0      4.0
1         2  Chennai Super Kings       Mumbai Indians   20.0      5.0

   runs_scored  run_rate  target result  Chinnaswamy  Eden Gardens  Kotla  \
0        187.0      9.35   175.0    win        False         False  False
1        152.0      7.60   188.0   loss        False         False  False

   PCA Stadium  Sawai Mansingh  Uppal  Wankhede
0        False           False  False      True
1        False           False  False     False

In [29]:
df.head(2)

,match_id,batting_team,bowling_team,overs,wickets,runs_scored,run_rate,target,result,Chinnaswamy,Eden Gardens,Kotla,PCA Stadium,Sawai Mansingh,Uppal,Wankhede
0,1,Mumbai Indians,Chennai Super Kings,20.0,4.0,187.0,9.35,175.0,win,False,False,False,False,False,False,True
1,2,Chennai Super Kings,Mumbai Indians,20.0,5.0,152.0,7.60,188.0,loss,False,False,False,False,False,False,False

In [32]:
from sklearn.preprocessing import LabelEncoder 

le = LabelEncoder()
cat_cols = ['batting_team' , 'bowling_team' , 'result']
for col in cat_cols:
    df[col]=le.fit_transform(df[col])

df.head()

,match_id,batting_team,bowling_team,overs,wickets,runs_scored,run_rate,target,result,Chinnaswamy,Eden Gardens,Kotla,PCA Stadium,Sawai Mansingh,Uppal,Wankhede
0,1,3,0,20.0,4.0,187.0,9.35,175.0,1,False,False,False,False,False,False,True
1,2,0,3,20.0,5.0,152.0,7.60,188.0,0,False,False,False,False,False,False,False
2,3,6,2,20.0,3.0,175.0,10.20,189.0,1,True,False,False,False,False,False,False
3,4,2,6,20.0,7.0,163.0,8.15,205.0,0,False,False,False,False,True,False,False
4,5,1,5,20.0,5.0,178.0,8.75,165.0,1,False,False,True,False,False,False,False